unleashed_shorten_url:
    resource: "@UnleashedShortenUrlBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
