unleashed_homepage:
    path:     /
    defaults: { _controller: UnleashedShortenUrlBundle:Default:index }
    
unleashed_view:
    path:     /{urlCode}
    defaults: { _controller: UnleashedShortenUrlBundle:Default:view }
