services:
    shorten_url:
        class: Unleashed\ShortenUrlBundle\Services\ShortenUrlService
        arguments: [@validation]

    validation:
        class: Unleashed\ShortenUrlBundle\Services\ValidationService
