services:
    shorten_url:
        class: Unleashed\ShortenUrlBundle\Services\ShortenUrlService
        arguments: [@validation]

    validation:
        class: Unleashed\ShortenUrlBundle\Services\ValidationService
        
    kernel.listener.error_listener:
        class: Unleashed\ShortenUrlBundle\EventListener\ShortenUrlExceptionListener
        arguments: ["@templating", "@mailer"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

